/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as CompleteProfileRouteImport } from './routes/complete-profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedStudentIndexRouteImport } from './routes/_authenticated/student/index'
import { Route as AuthenticatedTeacherIndexRouteImport } from './routes/_authenticated/teacher/index'
import { Route as AuthenticatedStudentAssignmentsAssignmentIdRouteImport } from './routes/_authenticated/student/assignments.$assignmentId'
import { Route as AuthenticatedTeacherAssignmentsAssignmentIdRouteImport } from './routes/_authenticated/teacher/assignments.$assignmentId'
import { Route as AuthenticatedTeacherGradeSubmissionIdRouteImport } from './routes/_authenticated/teacher/grade.$submissionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteProfileRoute = CompleteProfileRouteImport.update({
  id: '/complete-profile',
  path: '/complete-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentIndexRoute =
  AuthenticatedStudentIndexRouteImport.update({
    id: '/student/',
    path: '/student/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherIndexRoute =
  AuthenticatedTeacherIndexRouteImport.update({
    id: '/teacher/',
    path: '/teacher/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentAssignmentsAssignmentIdRoute =
  AuthenticatedStudentAssignmentsAssignmentIdRouteImport.update({
    id: '/student/assignments/$assignmentId',
    path: '/student/assignments/$assignmentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherAssignmentsAssignmentIdRoute =
  AuthenticatedTeacherAssignmentsAssignmentIdRouteImport.update({
    id: '/teacher/assignments/$assignmentId',
    path: '/teacher/assignments/$assignmentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeacherGradeSubmissionIdRoute =
  AuthenticatedTeacherGradeSubmissionIdRouteImport.update({
    id: '/teacher/grade/$submissionId',
    path: '/teacher/grade/$submissionId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student/': typeof AuthenticatedStudentIndexRoute
  '/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/student/assignments/$assignmentId': typeof AuthenticatedStudentAssignmentsAssignmentIdRoute
  '/teacher/assignments/$assignmentId': typeof AuthenticatedTeacherAssignmentsAssignmentIdRoute
  '/teacher/grade/$submissionId': typeof AuthenticatedTeacherGradeSubmissionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/complete-profile': typeof CompleteProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/student': typeof AuthenticatedStudentIndexRoute
  '/teacher': typeof AuthenticatedTeacherIndexRoute
  '/student/assignments/$assignmentId': typeof AuthenticatedStudentAssignmentsAssignmentIdRoute
  '/teacher/assignments/$assignmentId': typeof AuthenticatedTeacherAssignmentsAssignmentIdRoute
  '/teacher/grade/$submissionId': typeof AuthenticatedTeacherGradeSubmissionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/complete-profile': typeof CompleteProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/student/': typeof AuthenticatedStudentIndexRoute
  '/_authenticated/teacher/': typeof AuthenticatedTeacherIndexRoute
  '/_authenticated/student/assignments/$assignmentId': typeof AuthenticatedStudentAssignmentsAssignmentIdRoute
  '/_authenticated/teacher/assignments/$assignmentId': typeof AuthenticatedTeacherAssignmentsAssignmentIdRoute
  '/_authenticated/teacher/grade/$submissionId': typeof AuthenticatedTeacherGradeSubmissionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/complete-profile'
    | '/register'
    | '/reset-password'
    | '/student/'
    | '/teacher/'
    | '/student/assignments/$assignmentId'
    | '/teacher/assignments/$assignmentId'
    | '/teacher/grade/$submissionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/complete-profile'
    | '/register'
    | '/reset-password'
    | '/student'
    | '/teacher'
    | '/student/assignments/$assignmentId'
    | '/teacher/assignments/$assignmentId'
    | '/teacher/grade/$submissionId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/complete-profile'
    | '/register'
    | '/reset-password'
    | '/_authenticated/student/'
    | '/_authenticated/teacher/'
    | '/_authenticated/student/assignments/$assignmentId'
    | '/_authenticated/teacher/assignments/$assignmentId'
    | '/_authenticated/teacher/grade/$submissionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CompleteProfileRoute: typeof CompleteProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-profile': {
      id: '/complete-profile'
      path: '/complete-profile'
      fullPath: '/complete-profile'
      preLoaderRoute: typeof CompleteProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/student/': {
      id: '/_authenticated/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof AuthenticatedStudentIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/': {
      id: '/_authenticated/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AuthenticatedTeacherIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/student/assignments/$assignmentId': {
      id: '/_authenticated/student/assignments/$assignmentId'
      path: '/student/assignments/$assignmentId'
      fullPath: '/student/assignments/$assignmentId'
      preLoaderRoute: typeof AuthenticatedStudentAssignmentsAssignmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/assignments/$assignmentId': {
      id: '/_authenticated/teacher/assignments/$assignmentId'
      path: '/teacher/assignments/$assignmentId'
      fullPath: '/teacher/assignments/$assignmentId'
      preLoaderRoute: typeof AuthenticatedTeacherAssignmentsAssignmentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teacher/grade/$submissionId': {
      id: '/_authenticated/teacher/grade/$submissionId'
      path: '/teacher/grade/$submissionId'
      fullPath: '/teacher/grade/$submissionId'
      preLoaderRoute: typeof AuthenticatedTeacherGradeSubmissionIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedStudentIndexRoute: typeof AuthenticatedStudentIndexRoute
  AuthenticatedTeacherIndexRoute: typeof AuthenticatedTeacherIndexRoute
  AuthenticatedStudentAssignmentsAssignmentIdRoute: typeof AuthenticatedStudentAssignmentsAssignmentIdRoute
  AuthenticatedTeacherAssignmentsAssignmentIdRoute: typeof AuthenticatedTeacherAssignmentsAssignmentIdRoute
  AuthenticatedTeacherGradeSubmissionIdRoute: typeof AuthenticatedTeacherGradeSubmissionIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedStudentIndexRoute: AuthenticatedStudentIndexRoute,
  AuthenticatedTeacherIndexRoute: AuthenticatedTeacherIndexRoute,
  AuthenticatedStudentAssignmentsAssignmentIdRoute:
    AuthenticatedStudentAssignmentsAssignmentIdRoute,
  AuthenticatedTeacherAssignmentsAssignmentIdRoute:
    AuthenticatedTeacherAssignmentsAssignmentIdRoute,
  AuthenticatedTeacherGradeSubmissionIdRoute:
    AuthenticatedTeacherGradeSubmissionIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CompleteProfileRoute: CompleteProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
